name: build_blend_env_image

on:
  push:
    paths:
      - 'Dockerfiles/Dockerfile.base_*'
      - '.github/workflows/build_blend_env_image.yml'
  workflow_dispatch:

jobs:
  build_blender_env_versioned:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Manually change these to match the blender image versions
        blender-version: ["2.93", "3.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders || :
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/Dockerfile.base_${{ matrix.blender-version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blender_env:${{ matrix.blender-version }}
          #cache-from: type=registry,ref=ulissigroup/vasp:cache
          #cache-to: type=registry,mode=max,ref=ulissigroup/vasp:cache,push=true
