name: Build blend_env image

env:
  DOCKERHUB_USERNAME: luciusm
  IMAGE_NAME: blender_env
  TEST_TAG: blender_env:tests
  LATEST_VERSION: '3.1'
  

on:
  push:
    branches:
      - main
      - workflow
    paths:
      - 'Dockerfiles/Dockerfile.base**'
      - '.github/workflows/build_blender_env_image.yml'
  workflow_dispatch:

jobs:
  build_blender_env_versioned:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Manually change these to match the blender image versions
        blender-version: ['3.0', '3.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders || :
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Login to Github Container Repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set lower case repository name
        # Hit at https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
        run: |
          echo "REPO_OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/Dockerfile.base_3.x
          push: true
          build-args: BLENDER_VERSION=${{ matrix.blender-version }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.IMAGE_NAME }}:blender${{ matrix.blender-version }}
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}:${{ matrix.blender-version }}
          # cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}:buildcache,mode=max
#           cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}:${{ matrix.blender-version }}
#           cache-to: type=inline
