# Test the batoms plugin using test
name: Test installation script

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop
  workflow_dispatch:
  
env:
  BLENDER_DOWN_URL: "https://mirror.clarkson.edu/blender/release"

jobs:
  install-linux:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      matrix:
        blender_ver: ["3.0.1", "3.1.0"]

    steps:
      - uses: actions/checkout@v2
      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     activate-environment: batoms
      # - name: Install basic tools
      #   run: |
      #     conda install -c conda-forge git curl python
      - name: Download portable blender
        run: |
          echo Currently install in $(pwd)
          VER=${{ matrix.blender_ver }}
          MAJ_VER=${VER%.*}
          echo $VER $MAJ_VER
          URL="${BLENDER_DOWN_URL}/Blender${MAJ_VER}/blender-${VER}-linux-x64.tar.xz"
          curl -O ${URL} && tar -xvf blender-*-linux-x64.tar.xz
          ls blender_*


